version: '3.8'
services:
  app:
    container_name: app
    build:
      args:
        user: laravel-blog
        uid: 1000
      context: ./docker/laravel
      dockerfile: Dockerfile
    working_dir: /var/www/code
    restart: unless-stopped
    volumes:
      - .:/var/www/code
    networks:
      - laravel-blog-network

  web:
    container_name: web
    image: nginx
    restart: unless-stopped
    working_dir: /var/www/code
    user: root
    volumes:
      - .:/var/www/code
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9999:80
    networks:
      - laravel-blog-network

  database:
    container_name: mysql
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - laravel-blog-database:/var/lib/mysql
      - ./docker/mysql/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - laravel-blog-network

  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - laravel-blog-network
    ports:
      - "${REDIS_PORT}:6379"

  npm:
    image: node:16
    working_dir: /var/www/code
    entrypoint: [ "npm" ]
    volumes:
      - "./www/:/var/www/code"

volumes:
  laravel-blog-database:
    driver: local

networks:
  laravel-blog-network:
    driver: bridge

